// INCLUDE FILE generated by "Pelles C for Windows, version 1.00".

#define WM_SHELLNOTIFY  WM_USER+5

#define TIMER_UHR       100
#define TIMER_UHRA      101
#define TIMER_STATUS    102

#define DLG_MAIN_X      1001
#define DLG_MAIN_Y      1002
#define DLG_MAIN_Z      1003
#define DLG_EDIT        1004
#define DLG_ALARM       1005
#define DLG_EVENTLIST   1006
#define DLG_INFO        1007
#define DLG_STATUS      1008

#define IDM_MENU        2001

#define IDR_ICO_MAIN    10001
#define IDR_ICO_TRAY    10002
#define IDR_ICO_TRAY2   10003
#define IDR_ICO_TRAY3   10004
#define IDR_ICO_TRAY4   10005

#define IDR_SND_FANFARE 11001

#define IDD_UHRZEIT     4001
#define IDD_RESTZEIT    4002
#define IDD_ENDZEIT     4003
#define IDI_ACLOCK      4004
#define IDD_EDIT        4005
#define IDI_BCLOCK      4006
#define IDD_5MIN        4007
#define IDD_15MIN       4008
#define IDD_30MIN       4009
#define IDD_60MIN       4010

#define IDD_WEITER      4011
#define IDD_STOPP       4014

#define IDD_ZEIT_AKT    4012
#define IDD_EVENT_AKT   4013

#define IDD_ZEIT_01     4015
#define IDD_ZEIT_02     4017
#define IDD_ZEIT_03     4019
#define IDD_ZEIT_04     4021
#define IDD_ZEIT_05     4023
#define IDD_ZEIT_06     4025
#define IDD_ZEIT_07     4027
#define IDD_ZEIT_08     4029
#define IDD_ZEIT_09     4031
#define IDD_ZEIT_10     4033
#define IDD_EVENT_01    4016
#define IDD_EVENT_02    4018
#define IDD_EVENT_03    4020
#define IDD_EVENT_04    4022
#define IDD_EVENT_05    4024
#define IDD_EVENT_06    4026
#define IDD_EVENT_07    4028
#define IDD_EVENT_08    4030
#define IDD_EVENT_09    4032
#define IDD_EVENT_10    4034
#define IDD_WT_01       4041
#define IDD_WT_02       4042
#define IDD_WT_03       4043
#define IDD_WT_04       4044
#define IDD_WT_05       4045
#define IDD_WT_06       4046
#define IDD_WT_07       4047
#define IDD_WT_08       4048
#define IDD_WT_09       4049
#define IDD_WT_10       4050
#define IDD_IN_LISTE    4035
#define IDD_STATUS      4036
#define IDD_WOCHENTAG   4037

#define IDACCEL         3001

#define IDS_ABOUT_FORM  5001

#define IDM_EDIT        6001
#define IDM_LIST        6014
#define IDM_MINI        6002
#define IDM_RESTZEIT    6003
#define IDM_EXIT        6004
#define IDM_RESTORE     6005
#define IDM_HIDE        6006
#define IDM_HIDEX       6007
#define IDM_HIDEY       6008
#define IDM_HIDEZ       6009
#define IDM_TOP         6010
#define IDM_TOPX        6011
#define IDM_TOPY        6012
#define IDM_TOPZ        6013
#define IDM_NEXT        6015
#define IDM_NOSOUND     6016
#define IDM_SORT        6017
#define IDM_INFO        6018
#define IDM_STATUS      6019



#define IDD_ALARM_TEXT  7001

#define IDD_EDIT_ZEIT   8001
#define IDD_EDIT_GRUND  8002
#define IDD_TEXT_ZEIT   8003
#define IDD_TEXT_GRUND  8004
#define IDD_TEXT_ENDE   8005
#define IDD_TEXT_INFO   8006
#define IDD_BTN_INFO    8007
